name: Python Script Workflow

on:
  workflow_dispatch:
    inputs:
      script-file:
        type: choice
        description: 'Script file to run'
        required: true
        default: 'Latest_Jobs.py'
        options:
          - admit_cards/admit_card.py
          - Latest_Jobs/Latest_Jobs.py
          - Latest_results/Latest_results.py

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"

      - name: Run Python script
        run: python ${{ github.workspace }}/${{ github.event.inputs.script-file }}

      - name: Run Python script and display result
        id: run-script
        continue-on-error: true
        run: |
          output=$(python ${{ github.workspace }}/${{ github.event.inputs.script-file }})
          echo "Script result: $output"


      - name: Upload artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: result-artifact
          path: Jobs.txt